/*
 * QEMU model of the CRP APB control registers for clock controller.
 *
 * Copyright (c) 2016 Xilinx Inc.
 *
 * Partly autogenerated by xregqemu.py 2016-08-19.
 * Written by Edgar E. Iglesias.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

{ .name = "rst-qspi", .fdt_index = 0, .range = 1 },
{ .name = "rst-ospi", .fdt_index = 1, .range = 1 },
/*
 * To avoid breaking backwards compatibility, we keep
 * PMC-SRST at index 2 and put SDIO0 and index 8.
 */
{ .name = "rst-ps-pmc-srst", .fdt_index = 2, .range = 1 },
{ .name = "rst-sdio1", .fdt_index = 3, .range = 1 },
{ .name = "rst-i2c", .fdt_index = 4, .range = 1 },
{ .name = "rst-gpio", .fdt_index = 5, .range = 1 },
{ .name = "rst-ps-pl-srst", .fdt_index = 6, .range = 1 },
{ .name = "rst-ps-ps-srst", .fdt_index = 7, .range = 1 },
/* SDIO0 at index 8, see above.  */
{ .name = "rst-sdio0", .fdt_index = 8, .range = 1 },
{ .name = "rst-ps-pl-por", .fdt_index = 9, .range = 1 },
{ .name = "rst-ps-ps-por", .fdt_index = 10, .range = 1 },
{ .name = "rst-ps-pmc-por", .fdt_index = 11, .range = 1 },
{ .name = "rst-nonps-sys3", .fdt_index = 12, .range = 1 },
{ .name = "rst-nonps-sys2", .fdt_index = 13, .range = 1 },
{ .name = "rst-nonps-sys1", .fdt_index = 14, .range = 1 },
{ .name = "rst-nonps-npi", .fdt_index = 15, .range = 1 },
{ .name = "rst-nonps-noc-por", .fdt_index = 16, .range = 1 },
{ .name = "rst-nonps-noc", .fdt_index = 17, .range = 1 },
{ .name = "rst-sbi", .fdt_index = 18, .range = 1 },
{ .name = "rst-pdma", .fdt_index = 19, .range = 2 },
{ .name = "rst-sysmon-cfg", .fdt_index = 21, .range = 1 },
{ .name = "rst-sysmon-seq", .fdt_index = 22, .range = 1 },
{ .name = "rst-pl", .fdt_index = 23, .range = 4 },
{ .name = "rst-usb", .fdt_index = 27, .range = 1 },
{ .name = "rst-dbg-reset", .fdt_index = 28, .range = 1 },
{ .name = "rst-dbg-dpc", .fdt_index = 29, .range = 1 },
