# Default configuration for microblazeel-softmmu

include microblaze-softmmu.mak
include pci.mak

CONFIG_XILINX_IOMODULE_UART=y
CONFIG_XILINX_IOMODULE_PIT=y
CONFIG_XILINX_IOMODULE_GPI=y
CONFIG_XILINX_IOMODULE_GPO=y
CONFIG_XILINX_IOMODULE_INTC=y
CONFIG_XLNX_ZYNQMP=y
CONFIG_SDHCI=y
CONFIG_SD=y
CONFIG_CADENCE=y
CONFIG_XILINX_SPIPS=y
CONFIG_ZYNQ_DEVCFG=y
CONFIG_DPCD=y
