/*
 * QEMU model of the CXTSGEN System Time Stamp Generator
 *
 * Copyright (c) 2014 Xilinx Inc.
 *
 * Autogenerated by xregqemu.py 2014-09-10.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

#include "hw/sysbus.h"
#include "hw/register.h"
#include "qemu/bitops.h"
#include "qemu/log.h"

#ifndef XILINX_CXTSGEN_ERR_DEBUG
#define XILINX_CXTSGEN_ERR_DEBUG 0
#endif

/* FIXME: This is ARM IP we should rebadge globally accordingly */

#define TYPE_XILINX_CXTSGEN "xilinx.cxtsgen"

#define XILINX_CXTSGEN(obj) \
     OBJECT_CHECK(CXTSGen, (obj), TYPE_XILINX_CXTSGEN)

REG32(COUNTER_CONTROL_REGISTER, 0x0)
    FIELD(COUNTER_CONTROL_REGISTER, EN, 1, 1)
    FIELD(COUNTER_CONTROL_REGISTER, HDBG, 1, 0)
REG32(COUNTER_STATUS_REGISTER, 0x4)
    FIELD(COUNTER_STATUS_REGISTER, DBGH, 1, 1)
REG32(CURRENT_COUNTER_VALUE_LOWER_REGISTER, 0x8)
REG32(CURRENT_COUNTER_VALUE_UPPER_REGISTER, 0xc)
REG32(BASE_FREQUENCY_ID_REGISTER, 0x20)

#define R_MAX (R_BASE_FREQUENCY_ID_REGISTER + 1)

typedef struct CXTSGen {
    SysBusDevice parent_obj;
    MemoryRegion iomem;

    bool enabled;
    uint64_t tick_offset;

    uint32_t regs[R_MAX];
    RegisterInfo regs_info[R_MAX];
} CXTSGen;

static void counter_control_postw(RegisterInfo *reg, uint64_t val64)
{
    CXTSGen *s = XILINX_CXTSGEN(reg->opaque);
    bool new_status = extract32(s->regs[R_COUNTER_CONTROL_REGISTER],
                                R_COUNTER_CONTROL_REGISTER_EN_SHIFT,
                                R_COUNTER_CONTROL_REGISTER_EN_LENGTH);
    uint64_t current_ticks;

    current_ticks = muldiv64(qemu_clock_get_us(QEMU_CLOCK_VIRTUAL),
                             get_ticks_per_sec(), 1000000);

    if ((s->enabled && !new_status) ||
        (!s->enabled && new_status)) {
        /* The timer is being disabled or enabled */
        s->tick_offset = current_ticks - s->tick_offset;
    }

    s->enabled = new_status;
}

static uint64_t couter_low_value_postr(RegisterInfo *reg, uint64_t val64)
{
    CXTSGen *s = XILINX_CXTSGEN(reg->opaque);
    uint64_t current_ticks, total_ticks;
    uint32_t low_ticks;

    if (s->enabled) {
        current_ticks = muldiv64(qemu_clock_get_us(QEMU_CLOCK_VIRTUAL),
                                 get_ticks_per_sec(), 1000000);
        total_ticks = current_ticks - s->tick_offset;
        low_ticks = (uint32_t) total_ticks;
    } else {
        /* Timer is disabled, return the time when it was disabled */
        low_ticks = (uint32_t) s->tick_offset;
    }

    return low_ticks;
}

static uint64_t couter_high_value_postr(RegisterInfo *reg, uint64_t val64)
{
    CXTSGen *s = XILINX_CXTSGEN(reg->opaque);
    uint64_t current_ticks, total_ticks;
    uint32_t high_ticks;

    if (s->enabled) {
        current_ticks = muldiv64(qemu_clock_get_us(QEMU_CLOCK_VIRTUAL),
                                 get_ticks_per_sec(), 1000000);
        total_ticks = current_ticks - s->tick_offset;
        high_ticks = (uint32_t) (total_ticks >> 32);
    } else {
        /* Timer is disabled, return the time when it was disabled */
        high_ticks = (uint32_t) (s->tick_offset >> 32);
    }

    return high_ticks;
}


static RegisterAccessInfo cxtsgen_regs_info[] = {
    {   .name = "COUNTER_CONTROL_REGISTER",  .decode.addr = A_COUNTER_CONTROL_REGISTER,
        .rsvd = 0xfffffffc, .post_write = counter_control_postw,
    },{ .name = "COUNTER_STATUS_REGISTER",  .decode.addr = A_COUNTER_STATUS_REGISTER,
        .rsvd = 0xfffffffd,
        .ro = 0x2,
    },{ .name = "CURRENT_COUNTER_VALUE_LOWER_REGISTER",  .decode.addr = A_CURRENT_COUNTER_VALUE_LOWER_REGISTER,
        .post_read = couter_low_value_postr,
    },{ .name = "CURRENT_COUNTER_VALUE_UPPER_REGISTER",  .decode.addr = A_CURRENT_COUNTER_VALUE_UPPER_REGISTER,
        .post_read = couter_high_value_postr,
    },{ .name = "BASE_FREQUENCY_ID_REGISTER",  .decode.addr = A_BASE_FREQUENCY_ID_REGISTER,
    }
};

static void cxtsgen_reset(DeviceState *dev)
{
    CXTSGen *s = XILINX_CXTSGEN(dev);
    unsigned int i;

    for (i = 0; i < ARRAY_SIZE(s->regs_info); ++i) {
        register_reset(&s->regs_info[i]);
    }

    s->tick_offset = 0;
    s->enabled = false;
}

static uint64_t cxtsgen_read(void *opaque, hwaddr addr, unsigned size)
{
    CXTSGen *s = XILINX_CXTSGEN(opaque);
    RegisterInfo *r = &s->regs_info[addr / 4];

    if (!r->data) {
        qemu_log("%s: Decode error: read from %" HWADDR_PRIx "\n",
                 object_get_canonical_path(OBJECT(s)),
                 addr);
        return 0;
    }
    return register_read(r);
}

static void cxtsgen_write(void *opaque, hwaddr addr, uint64_t value,
                      unsigned size)
{
    CXTSGen *s = XILINX_CXTSGEN(opaque);
    RegisterInfo *r = &s->regs_info[addr / 4];

    if (!r->data) {
        qemu_log("%s: Decode error: write to %" HWADDR_PRIx "=%" PRIx64 "\n",
                 object_get_canonical_path(OBJECT(s)),
                 addr, value);
        return;
    }
    register_write(r, value, ~0);
}

static const MemoryRegionOps cxtsgen_ops = {
    .read = cxtsgen_read,
    .write = cxtsgen_write,
    .endianness = DEVICE_LITTLE_ENDIAN,
    .valid = {
        .min_access_size = 4,
        .max_access_size = 4,
    },
};

static void cxtsgen_realize(DeviceState *dev, Error **errp)
{
    CXTSGen *s = XILINX_CXTSGEN(dev);
    const char *prefix = object_get_canonical_path(OBJECT(dev));
    unsigned int i;

    for (i = 0; i < ARRAY_SIZE(cxtsgen_regs_info); ++i) {
        RegisterInfo *r = &s->regs_info[cxtsgen_regs_info[i].decode.addr/4];

        *r = (RegisterInfo) {
            .data = (uint8_t *)&s->regs[
                    cxtsgen_regs_info[i].decode.addr/4],
            .data_size = sizeof(uint32_t),
            .access = &cxtsgen_regs_info[i],
            .debug = XILINX_CXTSGEN_ERR_DEBUG,
            .prefix = prefix,
            .opaque = s,
        };
    }
}

static void cxtsgen_init(Object *obj)
{
    CXTSGen *s = XILINX_CXTSGEN(obj);
    SysBusDevice *sbd = SYS_BUS_DEVICE(obj);

    memory_region_init_io(&s->iomem, obj, &cxtsgen_ops, s,
                          TYPE_XILINX_CXTSGEN, R_MAX * 4);
    sysbus_init_mmio(sbd, &s->iomem);
}

static const VMStateDescription vmstate_cxtsgen = {
    .name = TYPE_XILINX_CXTSGEN,
    .version_id = 1,
    .minimum_version_id = 1,
    .minimum_version_id_old = 1,
    .fields = (VMStateField[]) {
        VMSTATE_UINT32_ARRAY(regs, CXTSGen, R_MAX),
        VMSTATE_END_OF_LIST(),
    }
};

static void cxtsgen_class_init(ObjectClass *klass, void *data)
{
    DeviceClass *dc = DEVICE_CLASS(klass);

    dc->reset = cxtsgen_reset;
    dc->realize = cxtsgen_realize;
    dc->vmsd = &vmstate_cxtsgen;
}

static const TypeInfo cxtsgen_info = {
    .name          = TYPE_XILINX_CXTSGEN,
    .parent        = TYPE_SYS_BUS_DEVICE,
    .instance_size = sizeof(CXTSGen),
    .class_init    = cxtsgen_class_init,
    .instance_init = cxtsgen_init,
};

static void cxtsgen_register_types(void)
{
    type_register_static(&cxtsgen_info);
}

type_init(cxtsgen_register_types)
