obj-$(CONFIG_PETALOGIX_S3ADSP1800) += petalogix_s3adsp1800_mmu.o
obj-$(CONFIG_PETALOGIX_ML605) += petalogix_ml605_mmu.o
obj-$(CONFIG_XLNX_ZYNQMP_PMU) += xlnx-zynqmp-pmu.o
obj-y += boot.o
obj-$(CONFIG_FDT) += microblaze_generic_fdt.o fdt-generic-devices.o
